### PR TITLE
added url+zip deploy method

### PR DESCRIPTION
**Pull request by vognev**
I'd like to be able to define in which way function should be deployed (either as `zip+base64` or as `url+zip`)

for that, i'm going to implement deployment strategy, which will upload function .zip to s3 bucket and then replace `f.content` with actual url

not going to implement advanced functionality like deleting old .zips etc, just a pretty basic stuff

what community thinks about it?

### CODE REVIEW

**Comment by vognev** [comment]
> As long as you can also live in a setup that does not have it then why not.

`base64+zip` method still remains default one

**Comment by vognev** [comment]
@sebgoa so, any chance for this to be merged?

**Comment by sebgoa** [comment]
I would love to hear more about your kubeless use-case, would be great if you could contact me at runseb@gmail.com

@andresmgot might still be maintaining this codebase so I will let him to decide if he wants to merge or not.

**Comment by andresmgot** [comment]
Hi @vognev, thank you for the PR! Yes, I will check it and give feedback (long time I haven't add a major feature to this plugin so let me setup the environemtn and get back to you).

**Comment by vognev** [comment]
Docs update PR is here - https://github.com/serverless/serverless/pull/6721

**Comment by vognev** [comment]
@andresmgot pending things done

**Comment by andresmgot** [comment]
@vognev thanks!

**Pull request merged**
