### PR TITLE
Add Support for individually prepackaged functions

### PR DESCRIPTION
**Pull request by ddoowa**
Add the ability to deploy pre-packaged individual functions, details can be found in #190

### CODE REVIEW

**Comment by ddoowa** [comment]
@andresmgot I've committed the changes and verified it works against the setup i have, the example-tests are failing in the CI server i was unable to run them against my local cluster nor our environment. Do the tests require a specific cluster setup?

**Comment by andresmgot** [comment]
Thanks for the PR @ddoowa!. The error in the CI was not related to your changes (just some flakiness there).

**Comment by ddoowa** [comment]
Thanks for sorting that out @andresmgot, Any ETA on how soon this can be merged?

**Comment by andresmgot** [comment]
now :) (I was just waiting for the CI to finish)

**Pull request merged**
